### ISSUE TITLE
Jest rule for lines between it blocks

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/web-configs#126]
Add a jest rule for lines between it blocks in tests. There's a similar [rule](https://eslint.org/docs/rules/lines-between-class-members) one in eslint for class memebers. 

Something like:

```
//bad
describe('some feature', () => {
  it('does foo', () => {
    // foo things 
  });
  it('does bar', () => {
    // bar things
  });
});


//good
describe('some feature', () => {
  it('does foo', () => {
    // foo things 
  });

  it('does bar', () => {
    // bar things
  });
});
```

**Comment by jgodson** [comment]
I tried out [this one](https://www.npmjs.com/package/eslint-plugin-jest-formatting) and it seems to be great. The strict preset enables all the rules, which all make sense to me. I'll PR it 🙂

**Comment by ryanwilsonperkin** [comment]
Hey, my buddy made that package! I don't have strong feelings about this particular lint rule, but I think it's well-built
