### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by kaelig** [Shopify/web-configs#137]
We have to be thorough when upgrading dependencies. In order to democratize this process, we should provide a clear contribution path for those ([like me](https://github.com/Shopify/eslint-plugin-shopify/pull/63)) who wish to help.

- [ ] Mention steps / requirements for dependency updates
- [ ] Provide a template for each added rule (e.g. following the same outline as below)

```markdown
- **eslint-config-prettier:** [`v2.6.0...v2.9.0`](https://github.com/prettier/eslint-config-prettier/compare/v2.6.0...v2.9.0)
  - Added: The [implicit-arrow-linebreak] rule
  - Added: The [react/jsx-one-expression-per-line] rule.
  - Added: The [lines-around-comment] rule (as a [special
    rule][lines-around-comment-special]).
  - Added: The [no-unexpected-multiline] rule (as a [special
    rule][no-unexpected-multiline-special]).
```
- [ ] Require a changelog update
- [ ] For important/breaking changes: require the upgrade path to be documented

Do you see anything else? cc @GoodForOneFare @ismail-syed @lemonmade

**Comment by atesgoral** [comment]
@alexandcote Can this be closed with #181 or is there more work to be done?
