### ISSUE TITLE
Add best practices and enforced tooling for file naming/casing

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/web-configs#164]
A common question we get a lot is the naming convention/casing for files, folders, react classes, classes etc. 

We should document our suggestions on this and also provide tooling to enforce this via an eslint rule or something of that nature. I don't think eslint would be the right tool here as we're testing file/folder names, not actually source code;  but I could be wrong here.

**Comment by janiceblundell** [comment]
This is done from the documentation perspective.
