### ISSUE TITLE
[stylelint-plugin] Unknown rule shopify/content-no-strings

### ISSUE THREAD

**Issue by ben10code** [Shopify/web-configs#191]
## Overview

I was casually writing code and stumbled upon this linting error. Not sure if it's a bug, but looks like one 🤔 

`Unknown rule shopify/content-no-strings. stylelint(shopify/content-no-strings)`

![image](https://user-images.githubusercontent.com/59658889/95499432-42b55080-0973-11eb-8ed3-c6bf517004fa.png)

![image](https://user-images.githubusercontent.com/59658889/95499441-48129b00-0973-11eb-8c06-91d3aaf9e508.png)

Snippet from the screenshot:

```
  const imageMarkup = () => {
    let imageStyle = null;
    if (card.image && !selected) {
      imageStyle = {
        backgroundSize: 'cover',
        backgroundPosition: '50%',
        backgroundImage: `url(${card.image.src})`,
      };
    } else if (card.image && selected) {
      imageStyle = {
        backgroundSize: '70%',
        backgroundPosition: '50%',
        backgroundRepeat: 'no-repeat',
        backgroundImage: `url(${card.image.src})`,
      };
    } else {
      imageStyle = undefined;
    }

    return <div className={styles.Image} style={imageStyle} />;
  };
```

## Consuming repo

> What repo were you working in when this issue occurred?

Shopify/email

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by gmcgibbon** [comment]
The [rule](https://github.com/Shopify/web-configs/blob/main/packages/stylelint-plugin/rules/content-no-strings/content-no-strings.js) appears to be for non-localized content values in CSS. See [test](https://github.com/Shopify/web-configs/blob/main/packages/stylelint-plugin/rules/content-no-strings/content-no-strings.test.js). Your screenshot doesn't appear to have any content key in it. Was it a caching issue in VSCode or are you still experiencing this problem?

**Comment by gmcgibbon** [comment]
Closing this for now. If this is a still a problem feel free to re-open and clarify. Thanks!
