### ISSUE TITLE
prefer-module-scope-constants false positive for commonjs

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Shopify/web-configs#192]
## Overview

[`prefer-module-scope-constants`](https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/prefer-module-scope-constants.md) produces false positives with commonjs.

Example:

```js
const MY_VALUE = true;

module.exports = () => {
  console.log(MY_VALUE);
};
```

Expected result: no warnings from `prefer-module-scope-constants`.

Actual result: `1:7  error  You must place screaming snake case at module scope. If this is not meant to be a module-scoped variable, use camelcase instead  @shopify/prefer-module-scope-constants`

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/EvgenyOrekhov/eslint-config-hardcore

## Labels

- [x] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: eslint-plugin` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by EvgenyOrekhov** [comment]
Sorry if I messed up filling the issue template, but all those checkboxes are really confusing.

**Comment by gmcgibbon** [comment]
The code snippet
```
const FOO = true;

module.exports = () => {
  console.log(FOO);
};
```
appears to [pass](https://github.com/Shopify/web-configs/commit/47ba50b28d58bd84dbc03aec9b425afeedd4d851) when tested against eslint's rule tester for both v6 and v7. Looking at [the rule](https://github.com/Shopify/web-configs/blob/7280b1e2e6ee4b2759e2f10649e527f1ecf7c768/packages/eslint-plugin/lib/rules/prefer-module-scope-constants.js), `VariableDeclarator` should be provided with all variable declaration nodes by eslint. In isolation, the rule appears to work. Any ideas on how we can get a failing test?

**Comment by EvgenyOrekhov** [comment]
@gmcgibbon Try using `sourceType: 'script'` in `parserOptions`.
