### ISSUE TITLE
`@typescript-eslint/ban-types` rule is broken

### ISSUE THREAD

**Issue by alexandcote** [Shopify/web-configs#200]
## Overview
The `@typescript-eslint/ban-types` rule is broken. 
"Complex" types now need to be written like this: 

### Bad
```ts
type Foo = {hello: string}[]
```

### Good
```ts
type Foo = Array<{hello: string}>
```

But this conflicts with our [rule configuration](https://github.com/Shopify/web-configs/blob/c8035b095e71ab7d82458377bec0d7085c3a51b1/packages/eslint-plugin/lib/config/rules/typescript.js#L108).

[Temporary fix in `online-store-web`](https://github.com/Shopify/online-store-web/pull/8885/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5R46)

## Consuming repo
`eslint-plugin`

**Comment by BPScott** [comment]
When I was poking at this, I found that the fix was in the "@typescript-eslint/array-type" rule, and that adding the following to my local config stopped errors

`"@typescript-eslint/array-type": ["error", {"defaultOption": "array"}]`

**Comment by dahukish** [comment]
@BPScott @alexandcote can we close this then?
