### ISSUE TITLE
Add autocomplete linting config

### ISSUE THREAD

**Issue by gcornhill** [Shopify/web-configs#217]
## Overview
Would like to propose adding this config into our eslint config, to help against regression and accessibility issues from autocomplete.

```
'jsx-a11y/autocomplete-valid': [
      2,
      {
        inputComponents: ['TextField', 'Select'],
      },
    ],
```

## Motivation

As part of the [Autocomplete project](https://vault.shopify.io/projects/17459), adding in settings for correct autocomplete attributes for `web` .

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by dahukish** [comment]
Feel free to put up a PR to 👀 at 🙇
