### ISSUE TITLE
binary-assignment-parens conflicts with prettier

### ISSUE THREAD

**Issue by JaKXz** [Shopify/web-configs#250]
## Overview

When this rule is set to `"always"` it will throw eslint errors because the parens are auto-corrected away by prettier, e.g.

```ts
const x = 10;
const myBool = (x === 10);
```

gets autocorrected to 

```ts
const x = 10;
const myBool = x === 10;
```
---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by BPScott** [comment]
the [prettier config](https://github.com/Shopify/web-configs/blob/a462a54bb5cefe867534a812f4670bdb1ee321f2/packages/eslint-plugin/lib/config/prettier.js) turns off rules that conflict with prettier, including binary-assignment-parens. If you're using prettier then you should use the prettier config to avoid conflicts.
