### ISSUE TITLE
Drop ios 10,11,12 support in browserslist-config

### ISSUE THREAD

**Issue by BPScott** [Shopify/web-configs#271]
In our browserslist config we target ios/safari 10 as a minimum version. This is old and can be updated.

This is because Shopify mobile apps supported ios 10 and they sometimes rendered webviews that shown pages from web apps. Thus the web apps needed to support ios 10 too.

As part of the [Drop ios 10,11,12 Vault project](https://vault.shopify.io/projects/18219) mobile apps dropped support for ios 10,11 and 12, on June 1st. This meant the newest version of the apps will not install on ios versions older than 13. However there are existing apps already installed on ios 10/11/12 devices. The mobile team specified a guideline that web apps that render webviews used within mobile apps may drop support for older ios devices one month after the apps themselves drop support. See discussion in https://github.com/Shopify/core-issues/issues/23657.

As of July 1st (i.e. right now) we can drop support for ios 10,11 and 12 in our web properties - updating our minimum supported ios version to match the ios apps.

Use `npx browserlist "SOMEQUERY"` to determine the right query to use. I note strangely `npx browserslist "ios_saf >= 13.6"` does not return the known browser "ios_saf 13.4-13.7" yay bugs :(

Work to be done:

- [x] Confirm what the minimum supported version is - is it 13.0 or is it a point version? [This vault project update](https://vault.shopify.io/projects/18219#status-update-103391) suggests 13.6 is  the minimum ios version.
- [x] Determine the correct browserlist query to target our minimum supported browser
- [x] Update [https://github.com/Shopify/web-configs/blob/main/packages/browserslist-config/index.js](browserslist-config), changing the `safari` and `ios` keys. This is a breaking change. :: https://github.com/Shopify/web-configs/pull/274
- [x] Update `sewing-kit` to depend up on the new version of browserslist-config and release the change. Write a migration guide that tells people to update their local version fo `@shopify/browserslist-config` if they have one in place of the defaults sk provides :: https://github.com/Shopify/sewing-kit/pull/2788
- [x] Update web's [browserslist config](https://github.com/Shopify/web/blob/master/package.json#L12-L15) to use the the newest version :: https://github.com/Shopify/web/pull/46515
- [x] Update polaris-react's v7 branch's browserlist config (libraries can't extend from existing browserlists for transitive dependency weirdness reasons) - https://github.com/Shopify/polaris-react/blob/v7.0.0-release/package.json#L163-L164 :: https://github.com/Shopify/polaris-react/pull/4304
- [x] Tell people about this update with a slack message in web-foundations
- [x] Update https://vault.shopify.io/pages/1524-Browser-support with information about new ios version support

**Comment by BPScott** [comment]
Yo @jasonkemp9099, can you confirm what the minimum supported iOS version is now? https://vault.shopify.io/projects/18219#status-update-103391 suggests 13.6?

**Comment by jasonkemp9099** [comment]
@BPScott that's correct!

**Comment by BPScott** [comment]
All done!

Well, the version of sk containing the PR to update the browserslist config hasn't yet been released, but that'll be done soon enough
