### ISSUE TITLE
jsx-no-hardcoded-content modules not working for node-modules

### ISSUE THREAD

**Issue by benan789** [Shopify/web-configs#275]
## Overview

```
{
  allowStrings: false,
  allowNumbers: true,
  modules: {
    'react-i18next': {
      Trans: { allowStrings: true, allowNumbers: true },
    },
  },
}
```
still results in 

> Do not use hardcoded content as the children of the Trans component @shopify/jsx-no-hardcoded-content

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by dahukish** [comment]
Do you have an example of where this is being used?

**Comment by BPScott** [comment]
Try this again with v41.0.1. I believe #305 fixed this.
