### ISSUE TITLE
[Proposal] Add principle document for type safety

### ISSUE THREAD

**Issue by tzvipm** [Shopify/web-configs#32]
I propose the following, based on our seeming consensus on the web foundations team around type-safety:

1. Principle doc -> Compile-time over run-time failures
2. Decision doc -> Use TypeScript as our type-safety mechanism for web projects

Thoughts? @TheMallen @lemonmade

I'd be happy to contribute a PR with these docs

**Comment by lemonmade** [comment]
So definitely no disagreement on the decision doc. We have desperately needed that one for a long time, I've taken a few stabs at rough drafts of it over the past few months but never gotten it in a good enough state.

The principle is interesting to me. I am very hesitant to add a new principle, though this one is very interesting and does back a lot of the decisions we have made over time. I kind of feel that it is more of a rationale for/ more specific application of `implicit over automatic`; implicit constructs are almost always more statically analyzable and thus more able to be handled at compile time (we actually talk about this a bit in that principle). Thoughts?

**Comment by lemonmade** [comment]
So definitely no disagreement on the decision doc. We have desperately needed that one for a long time, I've taken a few stabs at rough drafts of it over the past few months but never gotten it in a good enough state.

The principle is interesting to me. I am very hesitant to add a new principle, though this one is very interesting and does back a lot of the decisions we have made over time. I kind of feel that it is more of a rationale for/ more specific application of `explicit over automatic`; explicit constructs are almost always

**Comment by TheMallen** [comment]
It also sort of ties into `declarative > imperative`, since types are a much more declarative system than any kind of runtime checking.
