### ISSUE TITLE
Upgrade eslint-plugin-prettier to support prettier v3

### ISSUE THREAD

**Issue by andyvanee** [Shopify/web-configs#392]
## Overview

Prettier 3.0.0 [has been released](https://github.com/prettier/prettier/releases). In our app, the only significant change was needing to upgrade to `eslint-plugin-prettier@^5.0.0` (which comes via `@shopify/eslint-plugin`)

- [StackOverflow reference](https://stackoverflow.com/a/76625797/807865)

## Consuming repo

- See backlink below

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by isaacbowen** [comment]
Very grateful y'all have these repos open. This issue helped unblock something important for us. :) Cheers!

**Comment by andyvanee** [comment]
Closed by https://github.com/Shopify/web-configs/pull/397
