### ISSUE TITLE
Document recommended project structures

### ISSUE THREAD

**Issue by lemonmade** [Shopify/web-configs#4]
- [ ] Rails app
- [ ] Node app
- [ ] Component-ey packages
- [ ] Regular packages

**Comment by tmlayton** [comment]
Would this documentation cover the highest level view of our opinions on how an application should be designed and built? We are not using an application framework, but seem to have clear conventions around this idea of everything is a React component, borrowing concepts from Rails routing and REST in terms of index, show, and create views, and loosely mimicking this using React Router. I’m wondering if that kind of information will be covered by these docs.

As a side note, I’m really curious to have a better understanding of what conventions we agree on and, if we are opinionated enough, wondering if it [eventually] makes sense to provide some tooling around this. Something like a `create-web-app` or a feather weight application framework that if focused on convention over configuration like Rails. From my point of view, the convention over configuration seems to be missing and IMO could cause friction for devs moving between Rails and web foundations projects.

Also, if any of my understanding if off please let me know.

**Comment by lemonmade** [comment]
Yes, this would cover the conventions you mentioned. It so happens we are working on just such a generator/ set of generators to make it easier to bootstrap and add to.
