### ISSUE TITLE
Figure out tools and patterns for E2E tests

### ISSUE THREAD

**Issue by lemonmade** [Shopify/web-configs#47]
https://github.com/Shopify/web/issues/1759

**Comment by TheMallen** [comment]
Conversation is ongoing about this in https://github.com/Shopify/u2/issues/3380.

The web team had looked into [Cypress]( https://www.cypress.io/) and liked it, but we ended up dropping it as e2e tests were not a priority for us at the time.

Given that Cypress does not support iframes, our secondary suggestion off hand is [Puppeteer](https://github.com/GoogleChrome/puppeteer) through [Jest](https://github.com/smooth-code/jest-puppeteer). Polaris has also used [Percy](https://percy.io/) for visual regression tests in particular.
