### ISSUE TITLE
Consider recommending Yarn offline mirror for apps

### ISSUE THREAD

**Issue by lemonmade** [Shopify/web-configs#57]
[Lee Byron recommends it](https://twitter.com/leeb/status/1017611690060312577), which is pretty high praise. cc/ @GoodForOneFare, curious on your thoughts.

**Comment by GoodForOneFare** [comment]
I'm not seeing the advantages.  If I'm just being dense, baking this into shopify-build would be grand.

Let's talk it through tomorrow in the pod.
