### ISSUE TITLE
Should we use Yarn's `set-version` policy?

### ISSUE THREAD

**Issue by lemonmade** [Shopify/web-configs#71]
This seems to me to be better than the annoying way Yarn upgrades/ versioning works right now. Thoughts? https://yarnpkg.com/en/docs/cli/policies

**Comment by lemonmade** [comment]
cc/ @GoodForOneFare @ismail-syed

**Comment by ismail-syed** [comment]
> checkin your Yarn release within your repository.

This should be ok as long as yarn release is stored in the repo so other environments (CI & shipit) can reference it. This seems like a new feature in [v1.13.0](https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#1130) so we'll have to update to this version org-wide
